gcp_credentials: ENCRYPTED[d3110e2399b82e1d2adb6f9294917064a448a4d102c42c5023815723841db4ff7aa1d0df64a44281ed25b3adbeb08eff]

linux_gc_task:
  use_compute_credits: true
  gce_instance:
    image_project: buildcluster-237411
    image_name: ubuntu18
    platform: linux
    zone: us-central1-c
    type: n1-highcpu-16    
    disk: 32
    use_ssd: true

  build_script: 
    - pwd; ls -la
    - chmod +x ./CI/build.sh
    - ./CI/build.sh